nav:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Hardware: Hardware/index.md
  - Home Assistant:
    - Screens: HomeAssistant/Screens/index.md
    - Custom Components: HomeAssistant/Components.md
    - Lovelace: HomeAssistant/Lovelace/index.md
    - Vacuum: HomeAssistant/Vacuum/index.md
    - Voice Control: HomeAssistant/VoiceControl/index.md
  - Software:
    - Overview: Software/Overview.md
    - Development: Software/Development.md
    - Upgrading: Software/Upgrading.md 
    - Ports: Software/Ports.md
    - Encryption: Software/Encryption.md
    - Apps: Software/Apps.md
    - Backup: Software/Backup.md
theme:
  favicon: images/favicon.png
  logo: 'logo.svg'
  font:
    text: Fira Code
    code: Fira Code
  name: 'material'
  custom_dir: overrides
  # palette:
  #   primary: 'Pink'
  #   accent: 'Pink'
repo_name: 'twhite96/SuburbanSmarts'
repo_url: 'https://github.com/twhite96/SuburbanSmarts'
extra:
  disqus: 'SuburbanSmarts'
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://suburbansmarts.org'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/twhite96/SuburbanSmarts'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/SuburbanSmarts'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCANizz_NF-Xr6DrnSLg0Ogg'
copyright: 'Copyright &copy; 2021 Tiffany White'
site_author: 'Tiffany White'
site_name: Suburban Smarts
site_url: 'https://docs.suburbansmarts.org/'
site_description: 'Documentation for my over-engineered smart apartment'
extra_css:
  - stylesheets/extra.css
markdown_extensions:
    - codehilite
    - smarty
    - toc:
        permalink: True
    - sane_lists