nav:
  - Home: index.md
  - Getting Started: Software/GettingStarted.md
  - Hardware: Hardware/index.md
  - Home Assistant:
    - Screens: HomeAssistant/Screens/index.md
    - Custom Components: HomeAssistant/Components.md
    - Lovelace: HomeAssistant/Lovelace/index.md
    - Vacuum: HomeAssistant/Vacuum/index.md
    - Voice Control: HomeAssistant/VoiceControl/index.md
  - Software:
    - Overview: Software/Overview.md
    - Development: Software/Development.md
    - Upgrading: Software/Upgrading.md 
    - Ports: Software/Ports.md
    - Encryption: Software/Encryption.md
    - Apps: Software/Apps.md
    - Backup: Software/Backup.md
theme:
  logo: 'logo.svg'
  font:
    code: Fira Code
  name: 'material'
  palette:
    primary: 'Pink'
    accent: 'Pink'
repo_name: 'twhite96/tw-homeassistant-config'
repo_url: 'https://github.com/twhite96/tw-homeassistant-config'
extra:
  disqus: docs-ss-org
  social:
    - icon: 'fontawesome/solid/rss'
      link: 'https://tiffanywhite.blog/categories/#smart-home-series'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/twhite96/tw-homeassistant-config'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/BravesFanPABaby'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCANizz_NF-Xr6DrnSLg0Ogg'
copyright: 'Copyright &copy; 2020 Tiffany White'
site_author: 'Tiffany White'
site_name: Suburban Smarts
site_url: 'https://docs.suburbansmarts.org/'
site_description: 'Documentation for my overengineered smart apartment'
